version: '3'
services:
  frontend:
    image: ghost:1-alpine
    ports: 
      - 2368:2368
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: mysql:5.7.40
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - database__client=mysql
      - database__connection__user=root
      - database__connection__password=root
      - database__connection__database=ghost
    volumes:
      - /dados-do-banco:/var/lib/mysql
    networks:
      - my-network
volumes:
  dados-do-banco:

networks:
  my-network: